services:
  db:
    image: postgres:18
    env_file:
      - .env
    volumes:
      - taskdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready","-U","${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


volumes:
  taskdata: